micronaut:
  application:
    name: bakeoff-micronaut
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

